In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sea
import numpy as nump
import sklearn as sk
%matplotlib inline

In [13]:
db = pd.read_csv('1_titanic_dataset.csv')

In [14]:
db.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [15]:
db.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [16]:
db.drop(['Cabin','PassengerId','Name','Ticket'], axis=1, inplace=True)
db.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [18]:
db.shape

(891, 8)

In [20]:
db.dropna(how='any', inplace =True)
db.shape

(712, 8)

In [30]:
db['Sex'].unique()

array(['male', 'female'], dtype=object)

In [39]:
db['Embarked'].unique()
db.drop(['Embarked'], axis=1,inplace=True)

In [38]:
n={'female':1,'male':0}
db['sex']=db['Sex'].map(n)
db.drop(["Sex"],axis=1,inplace= True)
db.head()

Survived  Pclass   Age  SibSp  Parch     Fare Embarked  sex
0         0       3  22.0      1      0   7.2500        S    0
1         1       1  38.0      1      0  71.2833        C    1
2         1       3  26.0      0      0   7.9250        S    1
3         1       1  35.0      1      0  53.1000        S    1
4         0       3  35.0      0      0   8.0500        S    0

In [40]:
db.head()

Survived  Pclass   Age  SibSp  Parch     Fare  sex
0         0       3  22.0      1      0   7.2500    0
1         1       1  38.0      1      0  71.2833    1
2         1       3  26.0      0      0   7.9250    1
3         1       1  35.0      1      0  53.1000    1
4         0       3  35.0      0      0   8.0500    0

In [41]:
X= db.drop(['Survived'], axis=1)
y=db['Survived']

In [42]:
X.head()

Pclass   Age  SibSp  Parch     Fare  sex
0       3  22.0      1      0   7.2500    0
1       1  38.0      1      0  71.2833    1
2       3  26.0      0      0   7.9250    1
3       1  35.0      1      0  53.1000    1
4       3  35.0      0      0   8.0500    0

In [43]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [83]:
db['Survived'].value_counts()

0    424
1    288
Name: Survived, dtype: int64

# Holdout

## Now that we got rid of all NaN and possibly useless columns we can start to work. First off comes holdout, it is a very simple method that its used for splitting the data into train and test, the idea behind it is to simply split the data in order to train the data with one set and to then test it with the other, it is usually done on rutine and the idea is to check that you are not overfitting the data.

In [44]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)

In [45]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)
predictions = dtree.predict(X_test)

In [47]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          0       0.76      0.80      0.78       123
          1       0.71      0.66      0.68        91

avg / total       0.74      0.74      0.74       214



In [48]:
print(confusion_matrix(y_test,predictions))

[[98 25]
 [31 60]]


In [49]:
from sklearn.svm import SVC
model = SVC()
model.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [50]:
predictions = model.predict(X_test)
print(confusion_matrix(y_test,predictions))

[[84 39]
 [34 57]]


In [51]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          0       0.71      0.68      0.70       123
          1       0.59      0.63      0.61        91

avg / total       0.66      0.66      0.66       214



## In this case we can see that the decision tree makes a much better model than the SVC

# Random Subsampling

## This step comes to validate the last one, in this case we resample the data and see if we got similar results in order to make sure that the model is working.

In [57]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size=0.30)

In [58]:
dtree.fit(X_train1,y_train1)
predictions1 = dtree.predict(X_test1)
print(classification_report(y_test1,predictions1))

             precision    recall  f1-score   support

          0       0.75      0.85      0.80       119
          1       0.77      0.64      0.70        95

avg / total       0.76      0.76      0.75       214



In [59]:
print(confusion_matrix(y_test1,predictions1))

[[101  18]
 [ 34  61]]


In [60]:
model.fit(X_train1,y_train1)
predictionsSVM1 = model.predict(X_test1)
print(confusion_matrix(y_test1,predictionsSVM1))

[[112   7]
 [ 55  40]]


In [61]:
print(classification_report(y_test1,predictionsSVM1))

             precision    recall  f1-score   support

          0       0.67      0.94      0.78       119
          1       0.85      0.42      0.56        95

avg / total       0.75      0.71      0.69       214



## As we can see the model changed quite a lot with the resampling

# Cross Validation

## Next comes Cross Validation, this means that we split the data into subsets and actually run all as tests and all as train data to make sure the model is not biased. So in this case we are splitting into 10, that means that 9 parts are used for training and 1 for tests, they try this 10 times.

In [70]:
from sklearn.model_selection import cross_val_score
scoretree= cross_val_score(dtree,X,y,cv=10)
scoreSVM= cross_val_score(model,X,y,cv=10)

In [71]:
scoretree

array([ 0.73611111,  0.70833333,  0.76388889,  0.80555556,  0.8028169 ,
        0.78873239,  0.8028169 ,  0.71830986,  0.82857143,  0.84285714])

In [72]:
scoreSVM

array([ 0.625     ,  0.55555556,  0.61111111,  0.72222222,  0.69014085,
        0.74647887,  0.69014085,  0.73239437,  0.72857143,  0.74285714])

In [73]:
scoretree.mean()

0.77979935166554881

In [74]:
scoreSVM.mean()

0.68444723898949245

## Here we can see that we get different results from different sets, but still if we get the mean the tree is a much better product in general

# Stratified Sampling

## In this case, we take a sample that is proportional to the population, so let say here we know that roughly only 1/3 of the people survived, this would actually make 1/3 of the sample from survived and 2/3 of the people who didn't.

In [90]:
from sklearn.model_selection import StratifiedShuffleSplit
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.3)

In [99]:
sss.get_n_splits(X, y)
model.fit(X_train,y_train)
predictionsSVM2 = model.predict(X_test)
print(confusion_matrix(y_test,predictionsSVM2))

[[84 39]
 [34 57]]


In [100]:
print(classification_report(y_test1,predictionsSVM2))

             precision    recall  f1-score   support

          0       0.55      0.55      0.55       119
          1       0.44      0.44      0.44        95

avg / total       0.50      0.50      0.50       214



In [101]:
dtree.fit(X_train,y_train)
predictions2 = dtree.predict(X_test)
print(classification_report(y_test,predictions2))

             precision    recall  f1-score   support

          0       0.77      0.80      0.78       123
          1       0.71      0.68      0.70        91

avg / total       0.75      0.75      0.75       214



In [102]:
print(confusion_matrix(y_test,predictions2))

[[98 25]
 [29 62]]


# Boot Straping